### ISSUE TITLE
大佬，使用中当红包的产生速度小的时候有卡顿的问题么？

### ISSUE THREAD

**Issue by duanwenxiang** [wenzi0github/firework-redpack-rain#3]

**Comment by wenzi0github** [comment]
没有遇到过卡顿的问题。

不过你说的这个“速度小”，是有多小呢？

**Comment by duanwenxiang** [comment]
> 没有遇到过卡顿的问题。
> 
> 不过你说的这个“速度小”，是有多小呢？

我设置的 200ms 在真机设备上出现卡顿的情况

**Comment by wenzi0github** [comment]
200ms是不是太快了些，每秒产生5个红包！

我们之前在实际的跨年活动场景里，我忘了设置的产生红包的时间间隔是多少了，不过是真人尽量能全部点中的产生速度。
